name: inOrbit CD

on:
  workflow_run:
    workflows: ['Docker Image CD']

jobs:
  deploy:
    name: Deploy to Vultr
    runs-on: ubuntu-latest

    steps:
      - name: connect SSH and deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VULTR_IP }}
          username: dockeruser
          key: ${{ secrets.VULTR_SSH_SECRET_KEY }}
          script: |
            cd /home/dockeruser/apps/inorbit
            docker pull dkadadev/inorbit-web:latest
            docker compose up -d web
